deb-eeprom: `maintenance`
Signed-off-by: Patrick Yavitz <pyavitz@xxxxx.com>

diff --git a/deb-eeprom b/deb-eeprom
--- a/deb-eeprom
+++ b/deb-eeprom
@@ -14,6 +14,22 @@ TXT="\033[0m"
 YLW="\e[0;33m"
 FIN="\e[0m"
 
+if [[ `command -v wget` ]]; then
+	[[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]];
+else
+	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
+		echo -e "${TXT}Installing missing depends${FIN}."
+		sudo apt update
+		sudo apt upgrade -y
+		sudo apt install -y wget
+	else
+		echo -e "This script requires an internet connection."
+		exit 0
+	fi
+fi
+
+if [[ `command -v aria2c` ]]; then :; else sudo apt update; sudo apt upgrade -y; sudo apt install -y aria2; fi
+
 echo_bdone(){
 echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
 }
@@ -50,7 +66,7 @@ sudo chmod +x /usr/local/bin/deb-eeprom
 sudo chmod +x /usr/local/bin/write2usb
 if [ -e /usr/local/bin/deb-eeprom ]; then sudo rm -f /usr/local/bin/deb-eeprom.orig; else sudo mv -f /usr/local/bin/deb-eeprom.orig /usr/local/bin/deb-eeprom; fi
 if [ -e /usr/local/bin/write2usb ]; then sudo rm -f /usr/local/bin/write2usb.orig; else sudo mv -f /usr/local/bin/write2usb.orig /usr/local/bin/write2usb; fi
-deb-eeprom -h
+deb-eeprom
 }
 
 cleaning(){
@@ -71,37 +87,37 @@ if [ -e /usr/local/bin/deb-eeprom-update ]; then sudo rm -f /usr/local/bin/deb-e
 
 builddir(){
 echo ""
-echo -en "${PNK}[${FIN}${TXT}Setup${FIN}${PNK}]${FIN}"
+echo -en "Running setup "
 sleep 1s
 mkdir -p /home/$USER/.build/eeprom
 cd /home/$USER/.build/eeprom
 wget -cq ${PATCHES}rpi-eeprom-control.patch
 wget -cq ${PATCHES}rpi-eeprom-update.patch
 if ls /home/$USER/.build/eeprom/{rpi-eeprom-control.patch,rpi-eeprom-update.patch} > /dev/null 2>&1; then
-	echo_nok;
+	echo_bdone
 else
 	echo_fail
-	exit;
+	exit 1
 fi
 }
 
 find_eeprom(){
 EEPROM_VERSION=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==1) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
 if [[ `wget -S --spider ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
-	download_eeprom;
+	download_eeprom
 else
-	finding_eeprom;
+	finding_eeprom
 fi
 }
 
 finding_eeprom(){
 EEPROM_VERSION=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==10) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
 if [[ `wget -S --spider ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
-	download_eeprom;
+	download_eeprom
 else
 	error
 	cleaning
-	exit;
+	exit 1
 fi
 }
 
@@ -115,7 +131,7 @@ ${DOWNLOAD} ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz && echo_bdone
 
 build_eeprom(){
 echo ""
-echo -e "${RED}Installing rpi-eeprom${FIN} ..."
+echo -e "Updating rpi-eeprom ..."
 tar xf rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz
 tar xf rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
 rm -f rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
@@ -131,7 +147,7 @@ dpkg-buildpackage -us -nc -uc
 cd ..
 sudo dpkg -i *.deb
 cd ..
-echo -e "${RED}Done${FIN}."
+echo -e "Done."
 cd /home/$USER
 rm -fdr /home/$USER/.build/eeprom
 echo
@@ -140,78 +156,31 @@ echo "Update bootloader - sudo rpi-eeprom-update -a"
 echo
 }
 
-rite2usb(){
-sudo write2usb
+upgrade(){
+checking; builddir; find_eeprom; build_eeprom
 }
 
-upgrade_eeprom(){
-checking
-builddir
-find_eeprom
-build_eeprom
-}
-
-### CHECKS
-internet_check(){
-if [[ `command -v wget` ]]; then
-	[[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]];
-else
-	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
-		echo -e "${TXT}Installing missing depends${FIN}."
-		sudo apt update
-		sudo apt upgrade -y
-		sudo apt install -y wget;
-	else
-		echo -e "This script requires an internet connection."
-		exit;
-	fi
-fi
-}
-
-depends_check(){
-if [[ `command -v aria2c` ]]; then :; else sudo apt update; sudo apt upgrade -y; sudo apt install -y aria2; fi
-}
-
-internet_check
-depends_check
-# Commands
 if [ $# -eq 0 ]; then
-	echo "Missing options!"
-	echo "(run $0 -h for help)"
 	echo ""
-	exit 0
+	current
+	latest
+	echo ""
+	>&2 echo -e "Arguments: upgrade update"
+	exit 1
 fi
+case $1 in
+	echo ""
+	current
+	latest
+	echo ""
+	upgrade|update)
+	;;
+	*)
+	echo -e "Arguments: upgrade update" >&2
+	exit 1
+esac
 
-ECHO="false"
+EEPROM=`echo $1`
+$EEPROM
 
-while getopts "uUh" OPTION; do
-        case $OPTION in
-
-                U)
-                        ECHO="upgrade"
-                        ;;
-                u)
-                        ECHO="update"
-                        ;;
-                h)
-                        echo -e "${RED}Raspberry Pi 4B EEPROM Helper Script${FIN}"
-                        echo "Usage: "
-                        echo ""
-                        current
-                        latest
-                        echo ""
-                        echo "   -U       Upgrade eeprom package"
-                        echo "   -u       Update script"
-                        echo ""
-                        exit 0
-                        ;;
-
-        esac
-done
-
-if [ $ECHO = "upgrade" ]; then
-	upgrade_eeprom;
-fi
-if [ $ECHO = "update" ]; then
-	update;
-fi
+exit 0
