fanctrl: `improve bananapicm4 support`
Removed menu interface
Allow script to add by 5's
Example: If trip_point_3 is set to 55*C than trip_point_4 is set to 60*C

Signed-off-by: Patrick Yavitz <pyavitz@xxxxx.com>

diff --git a/fanctrl b/fanctrl
--- a/fanctrl
+++ b/fanctrl
@@ -35,150 +35,47 @@ echo -e "$WARNING_MSG"
 exit 0
 }
 
-trip_point0 (){
-TZONE0="/sys/devices/virtual/thermal/thermal_zone0/trip_point_0_temp"
-TZONE1="/sys/devices/virtual/thermal/thermal_zone1/trip_point_0_temp"
-TZONE2="/sys/devices/virtual/thermal/thermal_zone2/trip_point_0_temp"
-TZONE3="/sys/devices/virtual/thermal/thermal_zone3/trip_point_0_temp"
-if [[ -f "$TZONE0" ]] && [[ -f "$TZONE1" ]] && [[ -f "$TZONE2" ]] && [[ -f "$TZONE3" ]]; then
-	echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone{0,1,2,3}/trip_point_0_temp
-else
-	echo -e "You are missing a trip point?"
-	exit 0
-fi
-}
-
-trip_point3 (){
-if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp" ]]; then
-	echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
-else
-	echo -e "You are missing trip_point_3_temp?"
-	exit 0
-fi
-}
-
-65(){ # 65°C
-echo 'POINT="65000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-60(){ # 60°C
-echo 'POINT="60000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-55(){ # 55°C
-echo 'POINT="55000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-50(){ # 50°C
-echo 'POINT="50000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-45(){ # 45°C
-echo 'POINT="45000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-40(){ # 40°C
-echo 'POINT="40000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-35(){ # 35°C
-echo 'POINT="35000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-30(){ # 30°C
-echo 'POINT="30000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
-25(){ # 25°C
-echo 'POINT="25000"' | tee /etc/default/fanctrl > /dev/null 2>&1
-source /etc/default/fanctrl
-sleep .25
-fanctrl run
-}
-
 run (){ # run script
-if [[ "$BOARD" == "bananapicm4" || "$BOARD" == "odroidn2l" || "$BOARD" == "odroidn2plus" ]]; then
-	trip_point3
+if [[ "$BOARD" == "bananapicm4" ]]; then
+	if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp" ]]; then
+		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
+		if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp" ]]; then
+			X=`echo $POINT | sed 's/...$//'`
+			Y="5"
+			echo "$(($X+$Y))000" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp
+		fi
+	else
+		echo -e "You are missing trip_point_3_temp?"
+		exit 0
+	fi
+fi
+if [[ "$BOARD" == "odroidn2l" || "$BOARD" == "odroidn2plus" ]]; then
+	if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp" ]]; then
+		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
+	else
+		echo -e "You are missing trip_point_3_temp?"
+		exit 0
+	fi
 fi
 if [[ "$BOARD" == "odroidxu4" ]]; then
-	trip_point0
+	TZONE0="/sys/devices/virtual/thermal/thermal_zone0/trip_point_0_temp"
+	TZONE1="/sys/devices/virtual/thermal/thermal_zone1/trip_point_0_temp"
+	TZONE2="/sys/devices/virtual/thermal/thermal_zone2/trip_point_0_temp"
+	TZONE3="/sys/devices/virtual/thermal/thermal_zone3/trip_point_0_temp"
+	if [[ -f "$TZONE0" ]] && [[ -f "$TZONE1" ]] && [[ -f "$TZONE2" ]] && [[ -f "$TZONE3" ]]; then
+		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone{0,1,2,3}/trip_point_0_temp
+	else
+		echo -e "You are missing a trip point?"
+		exit 0
+	fi
 fi
 }
 
-menu (){
-while [ 1 ]
-do
-CHOICE=$(
-export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
-whiptail --backtitle "Current Trip Point: $POINT" --title "Fan Control" --menu "" --nocancel 0 0 0 \
-	"6)" "65°C" \
-	"5)" "55°C" \
-	"4)" "45°C" \
-	"3)" "35°C" \
-	"2)" "25°C" \
-	"E)" "Exit .." 3>&2 2>&1 1>&3
-)
-case $CHOICE in
-	"6)")
-		clear -x
-		fanctrl 65
-		export NEWT_COLORS='root=,black'
-		whiptail --msgbox "    Trip point set to 65°C" 0 0
-		;;
-	"5)")
-		clear -x
-		fanctrl 55
-		export NEWT_COLORS='root=,black'
-		whiptail --msgbox "    Trip point set to 55°C" 0 0
-		;;
-	"4)")
-		clear -x
-		fanctrl 45
-		export NEWT_COLORS='root=,black'
-		whiptail --msgbox "    Trip point set to 45°C" 0 0
-		;;
-	"3)")
-		clear -x
-		fanctrl 35
-		export NEWT_COLORS='root=,black'
-		whiptail --msgbox "    Trip point set to 35°C" 0 0
-		;;
-	"2)")
-		clear -x
-		fanctrl 25
-		export NEWT_COLORS='root=,black'
-		whiptail --msgbox "    Trip point set to 25°C" 0 0
-		;;
-	"E)")
-		clear -x
-		exit 0
-		;;
-	esac
-done
+temperature (){
+echo 'POINT="'"${X}000"'"' | tee /etc/default/fanctrl > /dev/null 2>&1
+source /etc/default/fanctrl
+sleep .25
+fanctrl run
 }
 
 update (){
@@ -204,17 +101,24 @@ fi
 }
 
 if [ $# -eq 0 ]; then
-	>&2 echo -e "Arguments: 65 60 55 50 45 40 35 30 25 menu run update"
+	>&2 echo -e "Arguments: 65 60 55 50 45 40 35 30 25 run update"
 	exit 1
 fi
 case $1 in
-	65|60|55|50|45|40|35|30|25|menu|run|update)
+	65|60|55|50|45|40|35|30|25|run|update)
 	;;
 	*)
-	echo -e "Arguments: 65 60 55 50 45 40 35 30 25 menu run update" >&2
+	echo -e "Arguments: 65 60 55 50 45 40 35 30 25 run update" >&2
 	exit 1
 esac
+
 FANCTRL=`echo $1`
-$FANCTRL
+$FANCTRL 2>/dev/null
+
+if [[ "$1" == "25" || "$1" == "30" || "$1" == "35" || "$1" == "40" || "$1" == "45" || \
+	"$1" == "50" || "$1" == "55" || "$1" == "60" || "$1" == "65" ]]; then
+	X="$1"
+	temperature
+fi
 
 exit 0
